version: "3.9"

services:
  backend:
    build:
      context: ./Server
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      DJANGO_SETTINGS_MODULE: "optomarket_back.settings"
    command: >
      sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    working_dir: /app/optomarket_back

  frontend:
    build:
      context: ./Client/optomarket
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
