version: '3.8'

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - optomarket-network
    volumes:
      - ./Client:/app
      - /app/node_modules

  server:
    build:
      context: ./Server/optomarket_back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - optomarket-network
    volumes:
      - ./Server/optomarket_back:/app
      - ./Server/optomarket_back/media:/app/media
      - ./Server/optomarket_back/static:/app/static
    command: python manage.py runserver 0.0.0.0:8000

networks:
  optomarket-network:
    driver: bridge
