# Generated by Django 6.0.3 on 2026-04-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_order_order_number_alter_order_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="seller_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
