# Generated by Django 6.0.3 on 2026-04-01 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_order_order_number_order_product_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="DEFAULT_ORDER", max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
            preserve_default=False,
        ),
    ]
