# Generated by Django 6.0.3 on 2026-04-21 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_product_is_with_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Скидка в процентах (0-100)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
