# Generated by Django 5.1.4 on 2026-04-21 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_product_discount_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Скидка в процентах (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
