# Generated by Django 6.0.3 on 2026-04-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_product_seller_name_product_seller_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
