# Generated by Django 6.0.3 on 2026-04-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_category_id_alter_order_id_alter_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_with_sale",
            field=models.BooleanField(default=False),
        ),
    ]
